import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import Navbar from '@/components/NavBar'
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <ToastContainer autoClose={2000}
          position="top-center"
          className="toast-container"
          toastClassName="dark-toast" />
      </body>
    </html>
  )
}
